### IMPORTS AND STUFF
import pygame
from pygame import *
from pygame.locals import *
from pygame_functions import *
from Animacion1 import *
import sys
import time
from random import randint


pygame.init()
pygame.mixer.init()


# Random Stuff
resolution = (800,600)
screen = pygame.display.set_mode((resolution))
pygame.display.set_caption("Minute War: Dark Melody")
pygame.display.set_icon(pygame.image.load("icon.png"))
clock_tick_rate=60
clock = pygame.time.Clock()

# Sounds (songs/effects)
pygame.mixer.music.load("intro.mp3")
pygame.mixer.music.play(0)

# Player Data
player = pygame.image.load("Sprites/Player/idle0.png")

player_location = [200,399]
vertical_momentum = 0
player_rect = pygame.Rect(200,399,36,57)
test_rect = pygame.Rect(200,399,100,50)

# Status NIVELES/PANTALLA
title_screen1 = True
title_screen2 = False
level1_forest = False
level2_desert = False
level3_castle = False


# NIVEL 1 - Data
background_forest0 = pygame.image.load("Background/01Templo/temple0.png")
background_forest1 = pygame.image.load("Background/02Forest/screen/forest_loop.png")
background_forest2 = pygame.image.load("Background/02Forest/screen/forest_boss.png")
backgdound_forest0 = pygame.transform.scale(background_forest0, (800, 600))

# NIVEL 2 - Data
background_desert0 = pygame.image.load("Background/03desert/screen/desert_loop.png")
background_desert1 = pygame.image.load("Background/03desert/screen/desert_final.png")
background_desert2 = pygame.image.load("Background/03desert/screen/desert_boss.png")



# Novel 3 - Data



# Funciones
def animation_intro1():
    screen.blit(freim1, [0, 0])
    time.sleep(0.04)
    pygame.display.update()    
    screen.blit(freim2, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim3, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim4, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim5, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim6, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim7, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim8, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim9, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim10, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim11, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim12, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim13, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim14, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim15, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim16, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim17, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim18, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim19, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim20, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim21, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim22, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim23, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim24, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim25, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim26, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim27, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim28, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim29, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim30, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim31, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim32, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim33, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim34, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim35, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim36, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim37, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim38, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim39, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim40, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim41, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim42, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim43, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim44, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim45, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim46, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim47, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim48, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim49, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim50, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim51, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim52, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim53, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim54, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim55, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim56, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim57, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim58, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim59, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim60, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim61, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim62, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim63, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim64, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim65, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim66, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim67, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim68, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim69, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim70, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim71, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim72, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim73, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim74, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim75, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim76, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim77, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim78, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim79, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim80, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim81, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim82, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim83, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim84, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim85, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim86, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim87, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim88, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim89, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim90, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim91, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim92, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim93, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim94, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim95, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim96, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim97, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim98, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim99, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim100, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim101, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim102, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim103, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim104, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim105, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim106, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim107, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim108, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim109, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim110, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim111, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim112, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim113, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim114, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim115, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim116, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim117, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim118, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim119, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim120, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim121, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim122, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim123, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim124, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim125, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim126, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim127, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim128, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim129, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim130, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim131, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim132, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim133, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim134, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim135, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim136, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim137, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim138, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim139, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim140, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim141, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim142, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim143, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim144, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim145, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim146, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim147, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim148, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim149, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim150, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim151, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim152, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim153, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim154, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim155, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim156, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim157, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim158, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim159, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim160, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim161, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim162, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim163, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim164, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim165, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim166, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim167, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim168, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim169, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim170, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim171, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim172, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim173, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim174, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim175, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim176, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim177, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim178, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim179, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim180, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim181, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim182, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim183, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim184, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim185, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim186, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim187, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim188, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim189, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim190, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim191, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim192, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim193, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim194, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim195, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim196, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim197, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim198, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim199, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim200, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim201, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim202, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim203, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim204, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim205, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim206, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim207, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim208, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim209, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim210, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim211, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim212, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim213, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim214, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim215, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim216, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim217, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim218, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim219, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim220, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim221, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim222, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim223, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim224, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim225, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim226, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim227, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim228, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim229, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim230, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim231, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim232, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim233, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim234, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim235, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim236, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim237, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim238, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim239, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim240, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim241, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim242, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim243, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim244, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim245, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim246, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim247, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim248, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim249, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim250, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim251, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim252, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim253, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim254, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim255, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim256, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim257, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim258, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim259, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim260, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim261, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim262, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim263, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim264, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim265, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim266, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim267, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim268, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim269, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim270, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim271, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim272, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim273, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim274, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim275, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim276, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim277, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim278, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim279, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim280, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim281, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim282, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim283, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim284, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim285, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim286, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim287, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim288, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim289, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim290, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim291, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim292, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim293, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim294, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim295, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim296, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim297, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim298, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim299, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim300, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim301, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim302, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim303, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim304, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim305, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim306, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim307, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim308, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim309, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim310, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim311, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim312, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim313, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim314, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim315, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim316, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim317, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim318, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim319, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim320, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim321, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim322, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim323, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim324, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim325, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim326, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim327, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim328, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim329, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim330, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim331, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim332, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim333, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim334, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim335, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim336, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim337, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim338, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim339, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim340, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim341, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim342, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim343, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim344, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim345, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim346, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim347, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim348, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim349, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim350, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim351, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim352, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim353, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim354, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim355, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim356, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim357, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim358, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim359, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim360, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim361, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim362, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim363, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim364, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim365, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim366, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim367, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim368, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim369, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim370, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim371, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim372, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim373, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim374, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim375, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim376, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim377, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim378, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim379, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim380, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim381, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim382, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim383, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim384, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim385, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim386, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim387, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim388, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim389, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim390, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim391, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim392, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim393, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim394, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim395, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim396, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim397, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim398, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim399, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim400, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim401, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim402, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim403, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim404, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim405, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim406, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim407, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim408, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim409, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim410, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim411, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim412, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim413, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim414, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim415, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim416, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim417, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim418, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim418, [0, 0])
    time.sleep(0.04)
    pygame.display.update()      
    screen.blit(freim419, [0, 0])
    time.sleep(0.04)
    pygame.display.update()      
    screen.blit(freim420, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim421, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim422, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim423, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim424, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim425, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim426, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim427, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim428, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim429, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim430, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim431, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim432, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim433, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim434, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim435, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim436, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim437, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim438, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim439, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim440, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim441, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim442, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim443, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim444, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim445, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim446, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim447, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim448, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim449, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim450, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim451, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim452, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim453, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim454, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim455, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim456, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim457, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim458, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim459, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim460, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim461, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim462, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim463, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim464, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim465, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim466, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(freim467, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    title_screen1 = False
    title_screen2 = True
def animation_intro2():
    screen.blit(background_image, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(background_image2, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(background_image3, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(background_image4, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
    screen.blit(background_image5, [0, 0])
    time.sleep(0.04)
    pygame.display.update()
def fadeout_screen(width, height): 
    fade = pygame.Surface((width, height))
    fade.fill((0,0,0))
    for alpha in range(0, 300):
        fade.set_alpha(alpha)
        #redrawWindow()
        screen.blit(fade, (0,0))
        pygame.display.update()
        pygame.time.delay(5)


# JUEGO - TITLE SCREEN1
while title_screen1 == True:
    
    screen.fill((84,0,150))

    for evento in pygame.event.get():
        if evento.type == QUIT:
            pygame.quit()
            sys.exit()
            
        if evento.type == KEYDOWN:
            if evento.key == K_x or evento.key == K_RETURN:
                pygame.mixer.music.fadeout(2500)
                time.sleep(2.5)
                title_screen1 = False
                title_screen2 = False
                level1_forest = True


    animation_intro1()
    title_screen1 = False
    title_screen2 = True

    pygame.display.update()
    pygame.display.flip()
    clock.tick(clock_tick_rate)






# JUEGO - TITLE SCREEN2
while title_screen2 == True:
    
    screen.fill((84,0,150))

    for evento in pygame.event.get():
        if evento.type == QUIT:
            pygame.quit()
            sys.exit()
            
        if evento.type == KEYDOWN:
            if evento.key == K_x or evento.key == K_RETURN:
                pygame.mixer.music.fadeout(2500)
                fadeout_screen(800,600)
                time.sleep(2.5)
                title_screen1 = False
                title_screen2 = False
                level1_forest = True


    animation_intro2()

    pygame.display.update()
    pygame.display.flip()
    clock.tick(clock_tick_rate)


# PLATER MOVEMENT STATUS
move_right = False
move_left = False
jump = False


player_rect.x = player_location[0]
player_rect.y = player_location[1]

# JUEGO - Level1
while level1_forest == True:
    pygame.mixer.music.stop()   
    screen.blit(background_forest0, [0, 0])

    for evento in pygame.event.get():
        if evento.type == QUIT:
            pygame.quit()
            sys.exit()

        # Teclas presionadas
        if evento.type == KEYDOWN:
            if evento.key == K_RIGHT:
                move_right = True
            if evento.key == K_LEFT:
                move_left = True
            if evento.key == True:
                vertical_momentum = -5
        if evento.type == KEYUP:
            if evento.key == K_RIGHT:
                move_right = False
            if evento.key == K_LEFT:
                move_left = False

    
    if move_right == True:
        player_rect.x += 8
    if move_left == True:
        player_rect.x -= 8
    if vertical_momentum > 3:
        vertical_momentum = 3



    '''
        if player_location[1] > resolution[1]-player.get_height():
            player_y_momentum = -player_y_momentum
        else:
            player_y_momentum += 0.2
        player_location[1] += player_y_momentum
        screen.blit(player, (player_location))
        if move_right == True:
            player_location[0] += 9
        if move_left == True:
            player_location[0] -= 9
    '''   

    # Rect + collision test

    if player_rect.colliderect(test_rect):
        pygame.draw.rect(screen,(255,0,0),test_rect)
    else:
        pygame.draw.rect(screen,(0,0,0),test_rect)
    # Más rect
    screen.blit(player,[player_rect.x,player_rect.y])




    pygame.display.update()
                            

    #pygame.display.update( )
    pygame.display.flip()
    clock.tick(clock_tick_rate)